### PR TITLE
Better environment setup

### PR DESCRIPTION
**Pull request by ajm188**
Makes char-rnn as a submodule inside the dependencies directory.
Adds a setup script to install all the lua dependencies. It makes sure torch is installed, and offers to install it for you if it's not.

Unfortunately you still have to install CUDA manually.

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
Weelp, I was going to do the submodule, but was waiting to actually update the README. Looks like good stuff.

**Comment by ajm188** [comment]
Hah sorry :/

**Comment by thomasrussellmurphy** [comment]
Well, I can still update the README after this all gets merged.

**Comment by ajm188** [comment]
:+1:

**Pull request merged**
